;
; 

;
; 

;
; 

;
; 


;
; 

;
; 

;
; 

;
; 

;
; 

;
; 

;
; 

;
; 

;
; 


;
; 

;
; 

;
; 


;
; 

  !(dynamic (/ parameter 2))
; 


;
; 

;
; 

;
; 



  (= 
    (parameter  verbosity 0) True)
; 


;
; 

;
; 

;
; 


  (= 
    (parameter  timing on) True)
; 



;
; 

;
; 

;
; 

;
; 

;
; 


  (= 
    (parameter  selection_method ask) True)
; 


;
; 

;
; 

;
; 

;
; 

;
; 


  (= 
    (parameter  assignment_method random) True)
; 


;
; 

;
; 

;
; 

;
; 

;
; 


  (= 
    (parameter  continuous yes) True)
; 



;
; 

;
; 

;
; 


  (= 
    (parameter  player_method human) True)
; 


;
; 

;
; 

;
; 


  (= 
    (parameter  opponent_method human) True)
; 



;
; 

;
; 

;
; 


  (= 
    (parameter  player_file none) True)
; 


;
; 

;
; 

;
; 


  (= 
    (parameter  opponent_file none) True)
; 



;
; 

;
; 

;
; 

;
; 


  (= 
    (parameter  verbose_interp on) True)
; 


;
; 

;
; 

;
; 

;
; 

;
; 

;
; 


  (= 
    (parameter  parsing_mode parsing) True)
; 


;
; 

;
; 

;
; 

;
; 

;
; 

;
; 

;
; 

;
; 

;
; 

;
; 

;
; 


  (= 
    (parameter  alpha_squares_mode off) True)
; 


;
; 

;
; 

;
; 

;
; 

;
; 

;
; 


  (= 
    (parameter  confirm_choices on) True)
; 



;
; 

;
; 

;
; 

;
; 

;
; 

;
; 


  (= 
    (parameter  completions on) True)
; 



;
; 

;
; 

;
; 

;
; 

;
; 

;
; 


  (= 
    (parameter  safety off) True)
; 



;
; 

;
; 

;
; 

;
; 

;
; 

;
; 


  (= 
    (parameter  compile_symmetries on) True)
; 




;
; 

;
; 

;
; 

;
; 

;
; 

;
; 

;
; 

;
; 




;
; 

;
; 

;
; 



;
; 

;
; 

;
; 

;
; 

;
; 


  (= 
    (parameter  random_min -1.0) True)
; 

  (= 
    (parameter  random_max 1.0) True)
; 


;
; 

;
; 

;
; 


  (= 
    (parameter  depth 1) True)
; 


;
; 

;
; 

;
; 

;
; 


;
; 

  (= 
    (parameter  game_time_limit 99999999) True)
; 



;
; 

;
; 

;
; 

;
; 

;
; 

;
; 

;
; 


  (= 
    (parameter  move_time_limit 10000) True)
; 


;
; 

;
; 

;
; 

;
; 

;
; 

;
; 

;
; 

;
; 

;
; 


  (= 
    (parameter  move_horizon 1) True)
; 



;
; 

;
; 

;
; 

;
; 


  (= 
    (parameter  ordering random) True)
; 



;
; 

;
; 

;
; 

;
; 


;
; 

;
; 

;
; 

;
; 


  (= 
    (parameter  discount exponent) True)
; 


;
; 

;
; 

;
; 


  (= 
    (parameter  vital_number 2) True)
; 
  

;
; 

;
; 

;
; 

;
; 


  (= 
    (parameter  possess_offset 2) True)
; 
  


