;                                           (convert-to-metta-file  tau_operators $_446228 sxx_machine/tau_operators.pl sxx_machine/tau_operators.metta)

  !(op 1170 xfx :-)
  !(op 1170 xfx -->)
  !(op 1170 fx :-)
  !(op 1170 fx ?-)
  !(op 500 yfx #)
  !(op 1150 fx dynamic)
  !(op 1150 fx meta-predicate)
  !(op 1150 fx package)
  !(op 1150 fx public)
  !(op 1150 fx import)
  !(op 1150 fx mode)
  !(op 1150 fx multifile)
  !(op 1150 fx block)



