;                                           (convert_to_metta_file  narsese $_283334 nars_lp/narsese.pl nars_lp/narsese.metta)
;
; Non-Axiomatic Logic in MeTTa
;
; Version: 1.1, September 2012
;
; GNU Lesser General Public License

  !(module narsese Nil)

  !(set-module (class library))
  !(set-module (base system))

  !(reexport (library (/ nars nars)))
  !(reexport (library (/ nars nal-reader)))



