;
;                           nal.pl

;
;                           Non-Axiomatic Logic in MeTTa

;
;                           Version: 1.1, September 2012

;
;                            GNU Lesser General Public License

;
;                            Author: Pei Wang/Pat Hammer/Douglas Miles



  !(module nal Nil)

  !(set-module (class library))
  !(set-module (base system))

  !(use-module (library (/ nars nal-reader))) 

  !(ensure-loaded nars)


