;
; 


;
; 


  (= 
    (ex  
      (colour  a red) +) True)
; 

  (= 
    (ex  
      (colour  b yellow) +) True)
; 


;
; 

  (= 
    (ex  
      (colour  
        (k  a a) red) +) True)
; 

  (= 
    (ex  
      (colour  
        (k  a b) red) +) True)
; 

  (= 
    (ex  
      (colour  
        (k  b b) yellow) +) True)
; 


;
; 

  (= 
    (ex  
      (colour  
        (k  a 
          (k  a a)) red) +) True)
; 

  (= 
    (ex  
      (colour  
        (k  a 
          (k  a b)) red) +) True)
; 

  (= 
    (ex  
      (colour  
        (k  a 
          (k  b b)) red) +) True)
; 

  (= 
    (ex  
      (colour  
        (k  b 
          (k  a a)) red) +) True)
; 

  (= 
    (ex  
      (colour  
        (k  b 
          (k  a b)) red) +) True)
; 

  (= 
    (ex  
      (colour  
        (k  b 
          (k  a b)) yellow) +) True)
; 

  (= 
    (ex  
      (colour  
        (k  b 
          (k  b b)) yellow) +) True)
; 


;
; 

  (= 
    (ex  
      (colour  
        (k  
          (k  a a) 
          (k  a a)) red) +) True)
; 

  (= 
    (ex  
      (colour  
        (k  
          (k  a a) 
          (k  a b)) red) +) True)
; 

  (= 
    (ex  
      (colour  
        (k  
          (k  a a) 
          (k  b b)) red) +) True)
; 

  (= 
    (ex  
      (colour  
        (k  
          (k  a b) 
          (k  a b)) red) +) True)
; 

  (= 
    (ex  
      (colour  
        (k  
          (k  a b) 
          (k  a b)) yellow) +) True)
; 

  (= 
    (ex  
      (colour  
        (k  
          (k  a b) 
          (k  b b)) red) +) True)
; 

  (= 
    (ex  
      (colour  
        (k  
          (k  a b) 
          (k  b b)) yellow) +) True)
; 

  (= 
    (ex  
      (colour  
        (k  
          (k  b b) 
          (k  b b)) yellow) +) True)
; 







; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 

