



  (= 
    (has-wings $X) 
    (bird $X))
; 


  (= 
    (has-beak $X) 
    (bird $X))
; 


  (= 
    (bird $X) 
    (vulture $X))
; 


  (= 
    (carnivore $X) 
    (vulture $X))
; 



  (= 
    (ex  
      (has_wings  tweety) +) True)
; 

  (= 
    (ex  
      (has_beak  tweety) +) True)
; 





; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 
; 

