
  (= 
    (features  
      ( (numeric minPrice) 
        (nominal tv) 
        (nominal bar))) True)
; 
                    ;
; 


;
; 

;
; 

;
; 



  (= 
    (case  
      (sheraton 250.0 y y)) True)
; 

  (= 
    (case  
      (ritz 223.0 y y)) True)
; 

  (= 
    (case  
      (kempinski 224.0 y y)) True)
; 

  (= 
    (case  
      (sonja 40.0 n y)) True)
; 

  (= 
    (case  
      (ostermann 35 n n)) True)
; 

  (= 
    (case  
      (zur_gruenen_wiese 50 y n)) True)
; 


