;;; -*- Mode: Lisp; Syntax: Common-lisp; Package: USER; -*-

(provide "TSPIN")
(in-package "USER")
(setq *warn-if-redefine* nil)
(defvar *FACTS*)
(defvar *RANDOM-AT-SAME-TIME*) 
(defvar *PROPERTY-STATES*)
(defvar *RANDOM-EVENTS*)
(defvar *PRESENT-CONTRACTIONS* )
(defvar *HAD-CONTRACTIONS*)
(defvar *EVERYONE-LOC-FACTS* )
(defvar *SAY-FACTS* )
(defvar *WORLD-FACTS*)
(defvar *trace*)
(defvar *yell*)
(load "tspin")
(load "mumble")
(load "verbs")
(load "data")
(load "objects")
(load "lisp-utils")
(load "cd-utils")
(load "cd-match")  
(load "sbl")
(load "convert")
(load "ltdl")
(load "patterns")