;                                           (convert_to_metta_file  dynamics $_152978 sre_dna/dynamics.pl sre_dna/dynamics.metta)
;
; ------------------------------------------------
;
; January 1999
;
; Author: Brian Ross
;
; Dept. of Computer Science, Brock University
;
; 
;
; dynamic definitions (make this the first file loaded)



  !(dynamic (/ individual 3))
  !(dynamic (/ newindividual 3))
  !(dynamic (/ popn-size-P 1))
  !(dynamic (/ best-so-far 4))
  !(dynamic (/ best-in-run 3))
  !(dynamic (/ gp-stats 8))
  !(dynamic (/ trace-count 2))
  !(dynamic (/ saved-trace 1))
  !(dynamic (/ popn-cnt 1))
  !(dynamic (/ current-run 1))
  !(dynamic (/ temp 1))
  !(dynamic (/ expression-type 1)) 


