;                                           (convert_to_metta_file  operators $_83624 sre_dna/operators.pl sre_dna/operators.metta)
;
; ------------------------------------------------
;
; Feb 1999
;
; Author: Brian Ross
;
; Dept. of Computer Science, Brock University
;
; 
;
; GP dctg operators
;
; 


  (= (?-  (op  480 xfy :))  True)
  (= (?-  (op  470 yfx *))  True)
  (= (?-  (op  470 yfx +))  True)


  (= (sre $E)  
    (write $E)
    (nl))



